COLUMNAS_ES = {
    "name": "nombre",
    "gamesPlayed": "partidos_jugados",
    "winRate": "porcentaje_victorias",
    "goals": "goles",
    "assists": "asistencias",
    "cleanSheetsDef": "porterías_cero_def",
    "cleanSheetsGK": "porterías_cero_portero",
    "shotSuccessRate": "porcentaje_tiros",
    "passesMade": "pases_completados",
    "passSuccessRate": "porcentaje_pases",
    "ratingAve": "valoracion_media",
    "tacklesMade": "entradas",
    "tackleSuccessRate": "porcentaje_entradas",
    "proName": "nombre_pro",
    "proPos": "posicion_pro",
    "proStyle": "estilo_pro",
    "proHeight": "altura_pro",
    "proNationality": "nacionalidad_pro",
    "proOverall": "media_general",
    "proOverallStr": "media_general_str",
    "manOfTheMatch": "mvps",
    "redCards": "rojas",
    "favoritePosition": "posicion_favorita"
}
